# Generated by Django 2.2 on 2019-04-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('full_name', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
