# Generated by Django 2.2 on 2019-04-20 17:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='default'),
        ),
    ]
