# Generated by Django 2.2 on 2019-04-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_menuitem_menuitemcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenu',
            name='parent_menu',
        ),
        migrations.DeleteModel(
            name='MainMenu',
        ),
        migrations.DeleteModel(
            name='SubMenu',
        ),
    ]
