# Generated by Django 2.2 on 2019-04-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190406_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='url',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='menuitemcategory',
            name='url',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
