# Generated by Django 2.2 on 2019-04-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_mainmenu_submenu_submenucategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='submenu',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submenucategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
