# Generated by Django 2.2 on 2019-04-06 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20190406_0239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submenucategory',
            options={'ordering': ['order']},
        ),
    ]
